#!/bin/sh
/home/pi/gst-rtsp-server-1.14.4/examples/test-launch --gst-debug=0 "( rpicamsrc bitrate=5000000 preview=false ! video/x-h264, width=1920, height=1080, framerate=30/1 ! h264parse ! rtph264pay name=pay0 pt=96 )"
